/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package artificial_vision_tracking;

import org.bytedeco.javacpp.Loader;
import org.bytedeco.javacv.FrameGrabber;
import org.bytedeco.opencv.opencv_java;
import org.opencv.aruco.Aruco;
import org.opencv.aruco.Dictionary;
import org.opencv.core.Mat;

import java.util.List;
import java.util.ArrayList;


public class App {
    /*static {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
    }*/
    static {
        // Carica le librerie native di OpenCV
        Loader.load(opencv_java.class);
    }
    public static void main(String[] args) throws FrameGrabber.Exception, InterruptedException {
        final int markersX = 2; // Numero di marker sull'asse X
        final int markersY = 2; // Numero di marker sull'asse Y
        final float markerLength = 0.03f; // Lunghezza del marker (in metri)
        final float markerSeparation = 0.007f; // Distanza tra i marker (in metri)
        final Dictionary dictionary = Aruco.getPredefinedDictionary(Aruco.DICT_4X4_100);
        final int selectedCamera = 1;

        //GenerateMarkersSheet gms = new GenerateMarkersSheet();
        //gms.generateMarkersSheet();
        //List<Mat> cameraParam = CameraCalibrator.calibration(markersX, markersY, markerLength, markerSeparation, dictionary);
        
        
        List<Mat> cameraParam = new ArrayList<>();
        Mat cameraMatrix = new Mat();
        Mat distCoeffs = new Mat();

        cameraMatrix = new Mat(3, 3, org.opencv.core.CvType.CV_64F);
        double[] data = {
            1.34481689e+03, 0.00000000e+00, 9.45455782e+02,
            0.00000000e+00, 1.34485743e+03, 5.71671069e+02,
            0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        };
        cameraMatrix.put(0, 0, data);

        distCoeffs = new Mat(1, 5, org.opencv.core.CvType.CV_64F);
        double[] data2 = {
            -3.66002754e-01, 8.58545102e-03, -8.16420804e-05, -1.02155112e-03, 2.81500718e-01
        };

        distCoeffs.put(0, 0, data2);

        cameraParam.add(cameraMatrix);
        cameraParam.add(distCoeffs);
        

        CameraPose.calcPose(cameraParam.get(0), cameraParam.get(1), markerLength, dictionary, selectedCamera);
        //MarkersDetector md = new MarkersDetector();
        //md.detect(dictionary, selectedCamera);
        //QrDetector qrDetector = new QrDetector();
        //qrDetector.detect();
    
    }
}